[package]
name = "raccoon-otel-demo"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1"
raccoon-otel = { path = ".." }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
